.TH ENCSPOT 1 "March 5, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
encspot \- guesses encoder used to create MP3 files
.SH SYNOPSIS
.B encspot
.RI [\fIFILE\fR]...
.SH DESCRIPTION
For a given list of MP3 files, \fBencspot\fP displays technical
information and attempts to determine which encoder was used to create
them. \fBencspot\fP also displays the contents of the LAME header
(if present).

.PP
.SH SEE ALSO
.BR mp3check (1),
.BR mp3info (1).
.\".br
.\"The programs are documented fully by
.\".IR "The Rise and Fall of a Fooish Bar" ,
.\"available via the Info system.
.SH AUTHOR
Written by GuerillaSoft.
.PP
This manual page was written by Francis Russell
<francis@unchartedbackwaters.co.uk>, for the Debian project (but may be
used by others).
