#!/bin/bash
set -e

VERSION=$(head -n1 debian/changelog | sed -r "s/.*\((.*)\).*/\1/") 
PACKAGE_NAME="encspot-${VERSION}"
TARBALL_NAME="${PACKAGE_NAME}.tar.bz2"
CURRENT_REVISION=$(mtn au get_current_revision | grep '^old_revision' | sed -r 's/old_revision \[(.*)\].*/\1/')
TEMP_DIR=$(mktemp -d)
SOURCE_DIR="${TEMP_DIR}/${PACKAGE_NAME}"
trap "rm -rf ${TEMP_DIR}" EXIT HUP INT QUIT TERM

mtn co -r ${CURRENT_REVISION} ${SOURCE_DIR}
rm -rf ${SOURCE_DIR}/{_MTN,make_tarball}
mtn log --no-files > ${SOURCE_DIR}/CHANGELOG
pushd ${TEMP_DIR}
tar -jcf "${TARBALL_NAME}" "${PACKAGE_NAME}"
popd
mv "${TEMP_DIR}/${TARBALL_NAME}" .
gpg --sign ${TARBALL_NAME}
